### ISSUE TITLE
Hover state retained on window exit

### ISSUE THREAD

**Issue by ghost** [linebender/xilem#13] opened 2022-11-27 22:08 UTC
https://user-images.githubusercontent.com/27787342/204162203-b5d94f8d-bd49-4453-8703-690667963831.mov

I suspect this is not intended behavior? All hover state should be discarded on cursor exiting the window.

**Comment by xStrom** [comment] 2022-12-03 16:00
Not intended and is not a problem in Druid last I checked. What macOS version do you have?

**Comment by leontepe** [comment] 2022-12-03 16:03
macOS Ventura 13.0.

**Comment by xStrom** [comment] 2022-12-03 16:22
I see you also commented on [glazier#38](https://github.com/linebender/glazier/pull/38) - does that not fix this issue?

**Comment by leontepe** [comment] 2022-12-03 16:32
Before that PR, hover didn’t work at all. With that PR it does, but it’s not reset on window exit.

**Comment by longmathemagician** [comment] 2022-12-03 17:07
This is a general druid shell / glazier event issue, the mouse leaving the window does not reset `IS_HOT` since the button is on the edge of the window. For whatever reason it stops sending mouse events when the cursor is outside the window.

At least on Windows this is actually a minor problem preventing platform-consistent implementation of button state management when you press, move the cursor outside the window, and then return it to the button to release.

**Comment by xStrom** [comment] 2022-12-03 19:35
That's interesting and certainly sounds like a regression. All of this worked back in 2020 when I implemented it. I also did very extensive testing, with some of those results being reported in [druid#828](https://github.com/linebender/druid/issues/828). I should revisit some of this stuff to see what's going on.

**Comment by longmathemagician** [comment] 2022-12-03 20:50
Interesting. IIRC you'll only trigger it for isolated widgets (ones not in a layout or other container) or if you miss a mouse move event (eventually an issue for pen/touch support) so it would definitely be an easy regression to miss.

**Comment by longmathemagician** [comment] 2022-12-08 03:23
I was able to reproduce this on linux and windows, turns out that mouse leave events were not being received in glazier or handled in xilem. The above draft PRs fix this (for x11) by adding a `MouseLeft` event. This could alternately be done just using `MouseMove` although doing so in druid was apparently problematic (https://github.com/linebender/druid/issues/852#issuecomment-913226105).

**Comment by longmathemagician** [comment] 2022-12-11 19:22
Could someone with macOS 13 confirm if this is now fixed?

**Comment by Cupnfish** [comment] 2022-12-12 03:14
https://user-images.githubusercontent.com/40173605/206952977-15f206e6-7711-44ea-aa40-25fb66fcda9a.mov

Seems to be no problem @longmathemagician

**Comment by longmathemagician** [comment] 2022-12-12 05:20
Awesome, thank you!

**Closed** 2022-12-12 05:20 UTC
